services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: fastapi_user
      DB_PASSWORD: password123
      DB_NAME: fastapi_db
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: scram-sha-256
      LISTEN_PORT: 6432
    ports:
      - "6432:6432"

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://fastapi_user:password123@pgbouncer:6432/fastapi_db
    volumes:
      - .:/app
    
    deploy:
      replicas: 3

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
volumes:
  postgres_data: